### ISSUE TITLE
Need CFB co-lead

### ISSUE THREAD

**Issue by vmatter-NOAA** [SEFSC-Caribbean-Strategic-Planning/LP23-Length-Comp#1]
Met with Kevin on 2/16 to discuss need.
Kevin agreed to assign someone from CFB
Next meeting is 3/15 and I'd like to meet with the co-lead before then so hoping to get someone assigned by 3/6 if possible

**Comment by RachelEckley-NOAA** [comment]
@smartinezrivera-NOAA will be the CFB co-lead.
